name: Deploy Lambda

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  deploy_zip:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    env:
      LAMBDA_NAME: iot_notifications_lambda
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Create Build Directory
        run: mkdir build

      - name: Pip Install
        run: pip install -r requirements.txt --target ./build

      - name: Copy Lambda Function
        run: cp -r ./src/* ./build

      - name: Clean compiled files
        run: find . -name '*.pyc' -delete

      - name: Create Zip File
        run: cd build && zip -r ../build.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Lambda Code and Set Environment Variables
        run: |
          aws lambda update-function-code \
            --function-name=$LAMBDA_NAME \
            --zip-file=fileb://build.zip

          aws lambda update-function-configuration \
            --function-name=$LAMBDA_NAME \
            --environment "Variables={DB_HOST=${{ secrets.DB_HOST }}, \
              DB_USER=${{ secrets.DB_USER }}, \
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}, \
              DB_NAME=${{ secrets.DB_NAME }}}"
